apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinedeployments.kubevm.io
spec:
  group: kubevm.io
  names:
    kind: VirtualMachineDeployment
    listKind: VirtualMachineDeploymentList
    plural: virtualmachinedeployments
    singular: virtualmachinedeployment
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualMachineDeployment is the Schema for the virtualmachinedeployments
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualMachineDeploymentSpec defines the desired state of VirtualMachineDeployment
          properties:
            replicas:
              format: int32
              minimum: 1
              type: integer
            template:
              description: VirtualMachineInstanceSpec defines the desired state of
                VirtualMachineInstance
              properties:
                image:
                  minLength: 1
                  type: string
                network:
                  minLength: 1
                  type: string
                status:
                  enum:
                  - Started
                  - Stopped
                  - Paused
                  type: string
              required:
              - image
              - network
              - status
              type: object
          required:
          - replicas
          - template
          type: object
        status:
          description: VirtualMachineDeploymentStatus defines the observed state of
            VirtualMachineDeployment
          properties:
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
