apiVersion: kubevm.io/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: example-virtualmachinedeployment
  label:
    app: testapp
spec:
  replicas: 2
  template:
    image: cirros-0.4.0
    network: subscriber-01
    status: Started

