apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachineinstances.kubevm.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.id
    description: VM identifier
    name: ID
    type: string
  - JSONPath: .spec.Status
    description: Desired VM Running Status
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: kubevm.io
  names:
    kind: VirtualMachineInstance
    listKind: VirtualMachineInstanceList
    plural: virtualmachineinstances
    singular: virtualmachineinstance
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualMachineInstance is the Schema for the virtualmachineinstances
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualMachineInstanceSpec defines the desired state of VirtualMachineInstance
          properties:
            image:
              minLength: 1
              type: string
            network:
              minLength: 1
              type: string
            status:
              enum:
              - Started
              - Stopped
              - Paused
              type: string
          required:
          - image
          - network
          - status
          type: object
        status:
          description: VirtualMachineInstanceStatus defines the observed state of
            VirtualMachineInstance
          properties:
            id:
              type: string
            status:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
