apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevm
  template:
    metadata:
      labels:
        name: kubevm
    spec:
      serviceAccountName: kubevm
      containers:
        - name: kubevm
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kubevm
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubevm"
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: kubevm
                  key: OS_AUTH_URL
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubevm
                  key: OS_USERNAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubevm
                  key: OS_PASSWORD
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: kubevm
                  key: OS_PROJECT_NAME
            - name: OS_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: kubevm
                  key: OS_DOMAIN_NAME

