kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevm
subjects:
- kind: ServiceAccount
  name: kubevm
roleRef:
  kind: Role
  name: kubevm
  apiGroup: rbac.authorization.k8s.io
